version: '3'

services:
  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/app
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # networks:
    #   - app-network

  nestle-vn:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost-nestlevn.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    #networks:
    #  - app-network

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    depends_on:
      - php
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   # networks:
     # - app-network

# networks:
#   app-network:
#     driver: bridge